k3s_version: v1.30.6+k3s1 # Phiên bản k3s cài cho cả master và worker
k3s_server_url: "https://{{ hostvars[groups['k3s_master'][0]].private_ip | default(hostvars[groups['k3s_master'][0]].ansible_default_ipv4.address) }}:6443" # Worker dùng URL này để join vào master
kubeconfig_local_path: "{{ playbook_dir }}/../kubeconfig" # Nơi lưu kubeconfig sau khi cài master
app_namespace: web-bansach # Namespace chính của ứng dụng
