apiVersion: v1 # API core Kubernetes
kind: Namespace # Tạo namespace
metadata:
  name: web-bansach # Namespace chạy ứng dụng
---
apiVersion: v1 # API core Kubernetes
kind: Namespace # Tạo namespace
metadata:
  name: monitoring # Namespace chạy Prometheus/Grafana
