apiVersion: v1
kind: ConfigMap
metadata:
  name: web-bansach-config
  namespace: web-bansach
data:
  MYSQL_DATABASE: DUAN_WEBBANSACH
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/DUAN_WEBBANSACH?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
  SPRING_DATASOURCE_USERNAME: root
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: web_bansach
  APP_FRONTEND_URL: https://hoanghh.xyz
  APP_BACKEND_URL: https://api.hoanghh.xyz
  APP_CORS_ALLOWED_ORIGINS: https://hoanghh.xyz
